### ISSUE TITLE
Lotus release handoff: FVM Sapphire (r09)

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/testnet-wallaby#18]
## Request

Please deploy the Wallaby testnet with the following Lotus release.

### Git reference

Branch: https://github.com/filecoin-project/lotus/tree/release/fevm-wallaby
Commit: [cb838cedae49106e9ceb7302add3688a835dbdb4](https://github.com/filecoin-project/lotus/commit/cb838cedae49106e9ceb7302add3688a835dbdb4)

### Scope

This release contains the release of [the Sapphire milestone](https://github.com/filecoin-project/ref-fvm/issues/940).

Headline items include:

- Bug fixes to the JSON-RPC API.
- Ethereum addresses are correctly assigned by CREATE.
- Slight performance improvements in EVM instruction dispatch.
- REVERT can now return a value.

**Comment by f8-fil-ops** [comment]
retired
