### ISSUE TITLE
Wallaby testnet looks unable to roll in

### ISSUE THREAD

**Issue by lyswifter** [filecoin-project/testnet-wallaby#5]
![DeepinScreenshot_select-area_20220909091358](https://user-images.githubusercontent.com/74490266/189251985-bde8d776-75f9-41ff-a0aa-40758f753285.png)

My genesis car file is correct and using the right commit, why can't load power actor?

**Comment by Stebalien** [comment]
How did you build?

**Comment by Stebalien** [comment]
And what branch?

**Comment by lyswifter** [comment]
I am using `experimental/fvm-m2` and  compiling with `make wallabynet`.

`commit c54145e337b8e21e22ea9bb45006122d0e13aa49 (HEAD -> experimental/fvm-m2, origin/experimental/fvm-m2)`

**Comment by Stebalien** [comment]
What's the output of `lotus --version` and `lotus version` (making sure both the client and server are using the same version)?

**Comment by lyswifter** [comment]
➜  lotus git:(experimental/fvm-m2) ./lotus --version
`lotus version 1.17.1-dev+wallabynet+git.c54145e33`

This is a little confusing for me. I compared the `md5sum` of local car file and the remote file:

➜  lotus git:(experimental/fvm-m2) md5sum build/genesis/wallabynet.car 
`3608fa4c16ad18c9bb0fba26f73a7234  build/genesis/wallabynet.car`

➜  Downloads md5sum wallabynet.car 
`3608fa4c16ad18c9bb0fba26f73a7234  wallabynet.car`

**Comment by Stebalien** [comment]
Ah, it looks like the wallaby testnet hasn't upgraded to the latest version. Checkout 65581c5aacd0f5e61e1cd9363310a1b0655b9611.

**Comment by Stebalien** [comment]
Ah... https://github.com/filecoin-project/lotus/pull/9269

**Comment by Stebalien** [comment]
No, I'm confused. @f8-ptrk what's the status of r2?
